// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdAmMAxzo3CIUt4coTeRlS-Jll9clfSek',
    appId: '1:679642292116:android:57520c569df34b6548f981',
    messagingSenderId: '679642292116',
    projectId: 'gestor-inv-2604190050',
    storageBucket: 'gestor-inv-2604190050.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHY81T0MyOn9259NhE-gbtzT7OAsRSohI',
    appId: '1:679642292116:ios:7d742a2f93bf2a2b48f981',
    messagingSenderId: '679642292116',
    projectId: 'gestor-inv-2604190050',
    storageBucket: 'gestor-inv-2604190050.firebasestorage.app',
    iosBundleId: 'com.jose.stitch.stitchApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB93Li47oLx1ZkTWVEFO8pUP6BVTXzV6Ug',
    appId: '1:679642292116:web:d23fd1f4b0a64e0b48f981',
    messagingSenderId: '679642292116',
    projectId: 'gestor-inv-2604190050',
    authDomain: 'gestor-inv-2604190050.firebaseapp.com',
    storageBucket: 'gestor-inv-2604190050.firebasestorage.app',
  );

}